# Force Transparent Huge Pages to madvise to eliminate memory compaction stutter on 4GB RAM
w /sys/kernel/mm/transparent_hugepage/enabled - - - - madvise
w /sys/kernel/mm/transparent_hugepage/defrag - - - - madvise
